// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxhnadjzwyrlkkwpaxlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4aG5hZGp6d3lybGtrd3BheGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NjMzOTEsImV4cCI6MjA4NDMzOTM5MX0.5xQkPjyY95clLWDZDiGD-KfkajwgFACzYLieAwbeFkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});